# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.gitlab.com/inzgiba/django_template
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: application.local
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: application.local
          servicePort: 80
  tls: []
  #  - secretName: application-tls
  #    hosts:
  #      - application.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nessProbe:
  httpGet:
    path: /health/
    port: django
    httpHeaders:
    - name: Host
      value: localhost
