version: '3.8'

services:
  django_template:
    tty: true
    build:
      context: ../..
      dockerfile: docker/Dockerfile
      args:
        DJANGO_ENV: development
    command: gunicorn sgi.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
    - .env
