apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ include "application.fullname" . }}
data:
  AWS_LOCATION: application
  AWS_S3_ENDPOINT_URL: https://fra1.digitaloceanspaces.com
  AWS_STORAGE_BUCKET_NAME: application-bucket
