apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ include "application.fullname" . }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUNDRVNTX0tFWV9JRA==
  AWS_SECRET_ACCESS_KEY: U0VDUkVUX0FDQ0VTU19LRVk=
