# Generated by Django 3.2.18 on 2023-03-25 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike_userss',
            field=models.ManyToManyField(blank=True, related_name='post_unlike_users', to=settings.AUTH_USER_MODEL, verbose_name='Кому не нравится'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='post_like_users', to=settings.AUTH_USER_MODEL, verbose_name='Кому нравится'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано'),
        ),
    ]
