apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  selector:
    matchLabels:
      app: application
  template:
    metadata:
      labels:
        app: application
    spec:
      containers:
      - name: application
        image: registry.gitlab.com/inzgiba/django_template:latest
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: django
          protocol: TCP
          containerPort: 8000
        envFrom:
        - configMapRef:
            name: application-config
        - secretRef:
            name: application-secret
        livenessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          httpGet:
            path: /health/
            port: django
            httpHeaders:
            - name: Host
              value: localhost
        readinessProbe:
          initialDelaySeconds: 30
          timeoutSeconds: 5
          httpGet:
            path: /health/
            port: django
            httpHeaders:
            - name: Host
              value: localhost
